hysteria.sm
50
hysteria.h
delay(4734.85);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(581.31);
press2_button(Down, Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Down, Right, self._duration);
delay(265.66);
press2_button(Left, Up, self._duration);
delay(265.66);
press2_button(Down, Right, self._duration);
delay(265.66);
press2_button(Up, Right, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Right, self._duration);
delay(265.66);
press2_button(Left, Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(423.48);
press_button(Left, self._duration);
delay(423.48);
press_button(Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(423.48);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(423.48);
press_button(Left, self._duration);
delay(423.48);
press_button(Right, self._duration);
delay(423.48);
press_button(Left, self._duration);
delay(581.31);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press2_button(Up, Right, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(581.31);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Up, self._duration);
delay(581.31);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Up, self._duration);
delay(896.97);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(896.97);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(423.48);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(423.48);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press2_button(Left, Up, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press_button(Down, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(265.66);
press_button(Left, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Up, self._duration);
delay(581.31);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(265.66);
press2_button(Left, Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Down, Up, self._duration);
delay(896.97);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(265.66);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(896.97);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(896.97);
press_button(Left, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Left, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(265.66);
press_button(Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press_button(Left, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(896.97);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(581.31);
press_button(Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Right, self._duration);
delay(581.31);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
delay(107.83);
press_button(Up, self._duration);
delay(107.83);
press_button(Down, self._duration);
delay(265.66);
press2_button(Left, Right, self._duration);
