#ifndef SONG_H
#define SONG_H
#include "helpers.h"
float press_duration = 50;
float bpm = 190.080002;

void play_song() {
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Down, Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Down, Right, press_duration);
  delay(266.92);
  press2_button(Left, Up, press_duration);
  delay(266.92);
  press2_button(Down, Right, press_duration);
  delay(266.92);
  press2_button(Up, Right, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Right, press_duration);
  delay(266.92);
  press2_button(Left, Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(425.38);
  press_button(Left, press_duration);
  delay(266.92);
  delay(158.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(425.38);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(425.38);
  press_button(Left, press_duration);
  delay(266.92);
  delay(158.46);
  press_button(Right, press_duration);
  delay(425.38);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press2_button(Up, Right, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(583.83);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Up, press_duration);
  delay(583.83);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Up, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  delay(158.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  delay(158.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(425.38);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press2_button(Left, Up, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Down, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Up, press_duration);
  delay(583.83);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(266.92);
  press2_button(Left, Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Down, Up, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Left, press_duration);
  delay(583.83);
  press_button(Left, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(266.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Left, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(583.83);
  delay(316.92);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  delay(316.92);
  press_button(Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Right, press_duration);
  delay(583.83);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(108.46);
  press_button(Up, press_duration);
  delay(108.46);
  press_button(Down, press_duration);
  delay(266.92);
  press2_button(Left, Right, press_duration);
  delay(1217.67);
}

#endif
