#ifndef SONG_H
#define SONG_H
#include "helpers.h"
float press_duration = 50;
float bpm = 115.09;

void play_song() {
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  delay(521.33);
  press_button(Down, press_duration);
  delay(992.66);
  press_button(Down, press_duration);
  delay(471.33);
  delay(521.33);
  press_button(Left, press_duration);
  delay(992.66);
  press_button(Down, press_duration);
  delay(471.33);
  delay(260.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(471.33);
  delay(1042.66);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Right, press_duration);
  delay(992.66);
  press_button(Right, press_duration);
  delay(471.33);
  delay(521.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  delay(260.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(471.33);
  delay(1042.66);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(732.00);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(2035.32);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  delay(260.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(471.33);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  delay(260.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(471.33);
  delay(521.33);
  press_button(Left, press_duration);
  delay(992.66);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Up, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Down, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(210.67);
  delay(521.33);
  press_button(Left, press_duration);
  delay(992.66);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(1644.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(341.00);
  delay(260.67);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(80.33);
  press_button(Up, press_duration);
  delay(80.33);
  press_button(Left, press_duration);
  delay(210.67);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(80.33);
  press_button(Down, press_duration);
  delay(80.33);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Left, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Right, press_duration);
  delay(471.33);
  press_button(Down, press_duration);
  delay(471.33);
  press_button(Up, press_duration);
  delay(2035.32);
}

#endif
